const NS = 'BARTERMATCH/PERFIL';

export const GET_PERFIL_REQUESTED = `${NS}/App/GET_PERFIL_REQUESTED`;
export const GET_PERFIL_FINISHED = `${NS}/App/GET_PERFIL_FINISHED`;
export const GET_PERFIL_ERROR = `${NS}/App/GET_PERFIL_ERROR`;

export const GET_MATCHS_REQUESTED = `${NS}/App/GET_MATCHS_REQUESTED`;
export const GET_MATCHS_FINISHED = `${NS}/App/GET_MATCHS_FINISHED`;
export const GET_MATCHS_ERROR = `${NS}/App/GET_MATCHS_ERROR`;
/* deDELETE publi */
export const DELETE_PUBLI_REQUESTED = `${NS}/App/DELETE_PUBLI_REQUESTED`;
export const DELETE_PUBLI_FINISHED = `${NS}/App/DELETE_PUBLI_FINISHED`;
export const DELETE_PUBLI_ERROR = `${NS}/App/DELETE_PUBLI_ERROR`;
