const NS = 'BARTERMATCH/HOMEPUBLI';

export const GET_PERFIL_REQUESTED = `${NS}/App/GET_PERFIL_REQUESTED`;
export const GET_PERFIL_FINISHED = `${NS}/App/GET_PERFIL_FINISHED`;
export const GET_PERFIL_ERROR = `${NS}/App/GET_PERFIL_ERROR`;