const NS = 'BARTERMATCH/HOMEPUBLI';

export const GET_PUBLIS_REQUESTED = `${NS}/App/GET_PUBLIS_REQUESTED`;
export const GET_PUBLIS_FINISHED = `${NS}/App/GET_PUBLIS_FINISHED`;
export const GET_PUBLIS_ERROR = `${NS}/App/GET_PUBLIS_ERROR`;
/* post publi */
export const POST_PUBLIS_REQUESTED = `${NS}/App/POST_PUBLIS_REQUESTED`;
export const POST_PUBLIS_FINISHED = `${NS}/App/POST_PUBLIS_FINISHED`;
export const POST_PUBLIS_ERROR = `${NS}/App/POST_PUBLIS_ERROR`;
/* deDELETE publi */
export const DELETE_PUBLI_REQUESTED = `${NS}/App/DELETE_PUBLI_REQUESTED`;
export const DELETE_PUBLI_FINISHED = `${NS}/App/DELETE_PUBLI_FINISHED`;
export const DELETE_PUBLI_ERROR = `${NS}/App/DELETE_PUBLI_ERROR`;