const NS = 'BARTERMATCH/HOMEPUBLI';

export const GET_PUBLIS_REQUESTED = `${NS}/App/GET_PUBLIS_REQUESTED`;
export const GET_PUBLIS_FINISHED = `${NS}/App/GET_PUBLIS_FINISHED`;
export const GET_PUBLIS_ERROR = `${NS}/App/GET_PUBLIS_ERROR`;