const NS = 'BARTERMATCH/HOMEPUBLI';

export const GET_MATCHS_REQUESTED = `${NS}/App/GET_MATCHS_REQUESTED`;
export const GET_MATCHS_FINISHED = `${NS}/App/GET_MATCHS_FINISHED`;
export const GET_MATCHS_ERROR = `${NS}/App/GET_MATCHS_ERROR`;