const NS = 'BARTERMATCH/HOMEPUBLI';

export const GET_MATCHS_REQUESTED = `${NS}/App/GET_MATCHS_REQUESTED`;
export const GET_MATCHS_FINISHED = `${NS}/App/GET_MATCHS_FINISHED`;
export const GET_MATCHS_ERROR = `${NS}/App/GET_MATCHS_ERROR`;
export const SET_SELECTED_USER = `${NS}/App/SET_SELECTED_USER`;
export const RESTORE_SELECTED_USER = `${NS}/App/RESTORE_SELECTED_USER`;

export const SET_MESSAGE_REQUESTED = `${NS}/App/SET_MESSAGE_REQUESTED`;
export const SET_MESSAGE_FINISHED = `${NS}/App/SET_MESSAGE_FINISHED`;
export const SET_MESSAGE_ERROR = `${NS}/App/SET_MESSAGE_ERROR`;
