openapi: 3.0.0
info:
  title: API Business Layer
  version: "0.1"
paths:

  /media:

    get:
      summary: Get Medias
      tags:
        - getMedia
      operationId: getMedias

      responses:
        '201':
          description: Add user confirmation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'

  /media/save:

    post:
      summary: Save medias
      tags:
        - media
      operationId: saveMedia

      requestBody:
        description: Save medias request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Media"
      responses:
        '201':
          description: Add user confirmation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'



components:
  schemas:

    getMediaResponse:
      description: ''
      type: object
      properties:
        media_list:
          $ref: '#/components/schemas/MediaList'
      required:
        - media_list

    MediaList:
      type: array
      items:
        $ref: '#/components/schemas/Media'

    Media:
      type: object
      description: ''
      required:
        - userId
        - urlPhoto
        - state
        - description
        - measures
      properties:
        userId:
          type: integer
        photoList:
          type: array
          items:
            $ref: '#/components/schemas/Photo'
        state:
          type: string
        description:
          type: string
        measures:
          type: string

    Photo:
      type: object
      description: ''
      properties:
        url:
          type: string

    MediaResponse:
      type: object
      description: ''
      properties:
        code:
          type: string
        message:
          type: string

    GeneralBusinessError:
      type: object
      description: 'Code that represents the error that took place'
      properties:
        code:
          type: string
        message:
          type: string
          description: Human readable description of the error

