openapi: 3.0.0
info:
  title: API Business Layer
  version: "0.1"
paths:

  /like/save:

    post:
      summary: Save like
      tags:
        - like
      operationId: saveLike

      requestBody:
        description: Save likes request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postLikeRequest"
      responses:
        '201':
          description: Add user confirmation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikeResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'



components:
  schemas:

    postLikeRequest:
      type: object
      description: ''
      required:
        - emailIssuing
        - mediaId
        - emailReceiver
      properties:
        emailIssuing:
          type: string
        mediaId:
          type: integer
        emailReceiver:
          type: string

    Like:
      type: object
      description: ''
      required:
        - userIssuing
        - mediaId
        - userReceiver
      properties:
        likeId:
          type: integer
        userIssuing:
          type: integer
        mediaId:
          type: integer
        userReceiver:
          type: integer

    LikeResponse:
      type: object
      description: ''
      properties:
        isMatch:
          type: boolean
        yourMedia:
          $ref: '#/components/schemas/MediaLike'
        otherMedia:
          $ref: '#/components/schemas/MediaLike'

    MediaLike:
      type: object
      description: ''
      required:
        - photoList
        - state
        - description
        - measures
        - title
        - color
        - brand
        - tag
      properties:
        mediaId:
          type: integer
        userEmail:
          type: string
        title:
          type: string
        color:
          type: string
        brand:
          type: string
        photoList:
          type: array
          items:
            $ref: '#/components/schemas/PhotoLike'
        state:
          type: string
        description:
          type: string
        measure:
          type: string
        tag:
          type: string
        updateDate:
          type: string
        dischargeDate:
          type: string

    PhotoLike:
      type: object
      description: ''
      properties:
        photoId:
          type: integer
        mediaId:
          type: integer
        url:
          type: string
          format: base64

    GeneralBusinessError:
      type: object
      description: 'Code that represents the error that took place'
      properties:
        code:
          type: string
        message:
          type: string
          description: Human readable description of the error

