openapi: 3.0.0
info:
  title: API Business Layer
  version: "0.1"
paths:

  /match/consult:

    post:
      summary: Post to get all matchs

      tags:
        - user

      operationId: getMatchs

      requestBody:
        description: Save likes request
        content:
          text/plain:
            schema:
              type: integer
      responses:
        '200':
          description: Get Match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchGetResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'

  /match/close:

    post:
      summary: Post to end a match

      tags:
        - user

      operationId: closeMatch

      requestBody:
        description: Save likes request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchRequest'
      responses:
        '200':
          description: Get Match
          content:
            application/json:
              schema:
                $ref: 'api-user.yml#/components/schemas/GeneralBusinessResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralBusinessError'



components:
  schemas:

    MatchRequest:
      description: ''
      type: object
      properties:
        matchId:
          type: integer
        reason:
          type: string
          enum:
            - Succes
            - Cancel

    MatchGetResponse:
      description: ''
      type: object
      properties:
        matchs:
          $ref: '#/components/schemas/Match_list'

    Match_list:
      type: array
      items:
        $ref: '#/components/schemas/Match'


    Chat:
      type: object
      description: ''
      required:
        - matchId1
        - userId2
        - state
      properties:
        matchId:
          type: string
        fotos:
          type: array
          items:
            type: string
        mensajes:
          type: array
          items:
            $ref: '#/components/schemas/Mensaje'

    Mensaje:
      type: object
      description: ''
      required:
        - userIssuing
        - userReceiver
        - dateTime
        - text
      properties:
        userIssuing:
          type: integer
        userReceiver:
          type: integer
        dateTime:
          type: string
        text:
          type: string


    Match:
      type: object
      description: ''
      required:
        - dateTimeMatch
        - userId1
        - userId2
        - state
      properties:
        dateTimeMatch:
          type: string
        mediaId1:
          type: integer
        mediaId2:
          type: integer
        state:
          type: string

    GeneralBusinessError:
      type: object
      description: 'Code that represents the error that took place'
      properties:
        code:
          type: string
        message:
          type: string
          description: Human readable description of the error

